# Generated by Django 5.1 on 2024-08-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(help_text='Ingrese el título del curso', max_length=200, verbose_name='Título del curso')),
                ('content', models.TextField(blank=True, help_text='Ingrese una descripción del curso', null=True, verbose_name='Descripción')),
                ('call_link', models.URLField(blank=True, help_text='Ingrese el enlace de llamada del curso', null=True, verbose_name='Enlace de llamada')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ingrese la fecha de creación del curso', null=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
