# Generated by Django 5.1 on 2024-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_show_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='toc',
            field=models.FileField(blank=True, help_text='Ingrese el archivo PDF con la tabla de contenidos del curso', null=True, upload_to='courses/tocs/%Y/%m/%d', verbose_name='Tabla de contenidos'),
        ),
    ]
