# Generated by Django 5.1 on 2024-08-15 20:19

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=thumbnails.fields.ImageField(blank=True, help_text='Ingrese la imagen del curso', null=True, upload_to='courses/images/', verbose_name='Imagen del curso'),
        ),
    ]
