# Generated by Django 5.1 on 2024-08-15 20:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Ingrese una descripción del curso', verbose_name='Descripción'),
        ),
    ]
