# Generated by Django 5.1 on 2024-08-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contant',
            new_name='Contact',
        ),
    ]
